Settings As screen:
    LoadingSpinnerColor: =RGBA(0, 120, 212, 1)

    Rectangle2_6 As rectangle:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderStyle: =BorderStyle.None
        BorderThickness: =2
        DisabledFill: =RGBA(161, 159, 157, 1)
        Fill: =RGBA(54, 176, 75, 1)
        FocusedBorderThickness: =4
        Height: =89
        HoverFill: =RGBA(0, 120, 212, 1)
        PressedFill: =RGBA(0, 120, 212, 1)
        Width: =640
        ZIndex: =1

    TextInput5 As text:
        BorderColor: =RGBA(245, 245, 245, 1)
        BorderThickness: =2
        Color: =RGBA(0, 0, 0, 1)
        Default: ="Cuentas"
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(161, 159, 157, 1)
        DisabledFill: =RGBA(242, 242, 241, 0)
        FocusedBorderThickness: =4
        Font: =Font.'Segoe UI'
        Height: =70
        HoverBorderColor: =RGBA(16, 110, 190, 1)
        HoverColor: =RGBA(50, 49, 48, 1)
        HoverFill: =RGBA(255, 255, 255, 1)
        PressedBorderColor: =RGBA(0, 120, 212, 1)
        PressedColor: =RGBA(50, 49, 48, 1)
        PressedFill: =RGBA(255, 255, 255, 1)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =21
        Width: =560
        X: =20
        Y: =142
        ZIndex: =2

    TextInput7 As text:
        BorderColor: =RGBA(245, 245, 245, 1)
        BorderThickness: =2
        Color: =RGBA(50, 49, 48, 1)
        Default: ="Acerca de"
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(161, 159, 157, 1)
        DisabledFill: =RGBA(242, 242, 241, 0)
        FocusedBorderThickness: =4
        Font: =Font.'Segoe UI'
        Height: =70
        HoverBorderColor: =RGBA(16, 110, 190, 1)
        HoverColor: =RGBA(50, 49, 48, 1)
        HoverFill: =RGBA(255, 255, 255, 1)
        PressedBorderColor: =RGBA(0, 120, 212, 1)
        PressedColor: =RGBA(50, 49, 48, 1)
        PressedFill: =RGBA(255, 255, 255, 1)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =21
        Width: =560
        X: =20
        Y: =335
        ZIndex: =4

    TextInput9 As text:
        BorderColor: =RGBA(245, 245, 245, 1)
        BorderThickness: =2
        Color: =RGBA(50, 49, 48, 1)
        Default: ="Tema"
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(161, 159, 157, 1)
        DisabledFill: =RGBA(242, 242, 241, 0)
        FocusedBorderThickness: =4
        Font: =Font.'Segoe UI'
        Height: =70
        HoverBorderColor: =RGBA(16, 110, 190, 1)
        HoverColor: =RGBA(50, 49, 48, 1)
        HoverFill: =RGBA(255, 255, 255, 1)
        PressedBorderColor: =RGBA(0, 120, 212, 1)
        PressedColor: =RGBA(50, 49, 48, 1)
        PressedFill: =RGBA(255, 255, 255, 1)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =21
        Width: =560
        X: =20
        Y: =416
        ZIndex: =5

    TextInput10 As text:
        BorderColor: =RGBA(245, 245, 245, 1)
        BorderThickness: =2
        Color: =RGBA(50, 49, 48, 1)
        Default: ="Cerrar sesión"
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(161, 159, 157, 1)
        DisabledFill: =RGBA(242, 242, 241, 0)
        FocusedBorderThickness: =4
        Font: =Font.'Segoe UI'
        Height: =70
        HoverBorderColor: =RGBA(16, 110, 190, 1)
        HoverColor: =RGBA(50, 49, 48, 1)
        HoverFill: =RGBA(255, 255, 255, 1)
        PressedBorderColor: =RGBA(0, 120, 212, 1)
        PressedColor: =RGBA(50, 49, 48, 1)
        PressedFill: =RGBA(255, 255, 255, 1)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =21
        Width: =560
        X: =79
        Y: =529
        ZIndex: =6

    Icon3 As icon.Leave:
        BorderColor: =RGBA(0, 0, 0, 0)
        Color: =RGBA(0, 120, 212, 1)
        DisabledBorderColor: =RGBA(245, 245, 245, 1)
        DisabledColor: =RGBA(225, 223, 221, 1)
        DisabledFill: =RGBA(0, 0, 0, 0)
        FocusedBorderThickness: =4
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverColor: =RGBA(16, 110, 190, 1)
        HoverFill: =RGBA(0, 0, 0, 0)
        Icon: =Icon.Leave
        PressedBorderColor: =RGBA(0, 0, 0, 0)
        PressedColor: =RGBA(16, 110, 190, 1)
        PressedFill: =RGBA(0, 0, 0, 0)
        X: =20
        Y: =529
        ZIndex: =7

    TextInput11 As text:
        BorderColor: =RGBA(245, 245, 245, 1)
        BorderThickness: =2
        Color: =RGBA(50, 49, 48, 1)
        Default: ="Notificaciones "
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(161, 159, 157, 1)
        DisabledFill: =RGBA(242, 242, 241, 0)
        FocusedBorderThickness: =4
        Font: =Font.'Segoe UI'
        Height: =70
        HoverBorderColor: =RGBA(16, 110, 190, 1)
        HoverColor: =RGBA(50, 49, 48, 1)
        HoverFill: =RGBA(255, 255, 255, 1)
        PressedBorderColor: =RGBA(0, 120, 212, 1)
        PressedColor: =RGBA(50, 49, 48, 1)
        PressedFill: =RGBA(255, 255, 255, 1)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =21
        Width: =560
        X: =20
        Y: =238
        ZIndex: =9

    Label4 As label:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderStyle: =BorderStyle.None
        BorderThickness: =2
        Color: =RGBA(50, 49, 48, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(161, 159, 157, 1)
        FocusedBorderThickness: =4
        Font: =Font.'Segoe UI'
        Height: =70
        Size: =40
        Text: ="Settings"
        Width: =560
        X: =80
        Y: =19
        ZIndex: =10

    Icon6_11 As icon.BackArrow:
        BorderColor: =RGBA(0, 0, 0, 0)
        Color: =RGBA(255, 255, 255, 1)
        DisabledBorderColor: =RGBA(245, 245, 245, 1)
        DisabledColor: =RGBA(225, 223, 221, 1)
        DisabledFill: =RGBA(0, 0, 0, 0)
        FocusedBorderThickness: =4
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverColor: =RGBA(0, 77, 41, 1)
        HoverFill: =RGBA(0, 0, 0, 0)
        Icon: =Icon.BackArrow
        OnSelect: =Navigate('Inicio o Registro',ScreenTransition.Fade)
        PressedBorderColor: =RGBA(0, 0, 0, 0)
        PressedColor: =RGBA(16, 110, 190, 1)
        PressedFill: =RGBA(0, 0, 0, 0)
        Y: =12
        ZIndex: =11

