Settings As screen:
    LoadingSpinnerColor: =RGBA(0, 120, 212, 1)

    Label2 As label:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderStyle: =BorderStyle.None
        BorderThickness: =2
        Color: =RGBA(50, 49, 48, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(161, 159, 157, 1)
        FocusedBorderThickness: =4
        Font: =Font.'Segoe UI'
        Height: =70
        Size: =40
        Text: ="Settings"
        Width: =533
        X: =107
        Y: =28
        ZIndex: =1

    TextInput5 As text:
        BorderColor: =RGBA(245, 245, 245, 1)
        BorderThickness: =2
        Color: =RGBA(50, 49, 48, 1)
        Default: ="Cuentas"
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(161, 159, 157, 1)
        DisabledFill: =RGBA(242, 242, 241, 0)
        FocusedBorderThickness: =4
        Font: =Font.'Segoe UI'
        Height: =70
        HoverBorderColor: =RGBA(16, 110, 190, 1)
        HoverColor: =RGBA(50, 49, 48, 1)
        HoverFill: =RGBA(255, 255, 255, 1)
        PressedBorderColor: =RGBA(0, 120, 212, 1)
        PressedColor: =RGBA(50, 49, 48, 1)
        PressedFill: =RGBA(255, 255, 255, 1)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =21
        Width: =560
        X: =20
        Y: =140
        ZIndex: =2

    Icon6 As icon.BackArrow:
        BorderColor: =RGBA(0, 0, 0, 0)
        Color: =RGBA(0, 120, 212, 1)
        DisabledBorderColor: =RGBA(245, 245, 245, 1)
        DisabledColor: =RGBA(225, 223, 221, 1)
        DisabledFill: =RGBA(0, 0, 0, 0)
        FocusedBorderThickness: =4
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverColor: =RGBA(16, 110, 190, 1)
        HoverFill: =RGBA(0, 0, 0, 0)
        Icon: =Icon.BackArrow
        PressedBorderColor: =RGBA(0, 0, 0, 0)
        PressedColor: =RGBA(16, 110, 190, 1)
        PressedFill: =RGBA(0, 0, 0, 0)
        X: =20
        Y: =34
        ZIndex: =3

    TextInput7 As text:
        BorderColor: =RGBA(245, 245, 245, 1)
        BorderThickness: =2
        Color: =RGBA(50, 49, 48, 1)
        Default: ="Acerca de"
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(161, 159, 157, 1)
        DisabledFill: =RGBA(242, 242, 241, 0)
        FocusedBorderThickness: =4
        Font: =Font.'Segoe UI'
        Height: =70
        HoverBorderColor: =RGBA(16, 110, 190, 1)
        HoverColor: =RGBA(50, 49, 48, 1)
        HoverFill: =RGBA(255, 255, 255, 1)
        PressedBorderColor: =RGBA(0, 120, 212, 1)
        PressedColor: =RGBA(50, 49, 48, 1)
        PressedFill: =RGBA(255, 255, 255, 1)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =21
        Width: =560
        X: =20
        Y: =346
        ZIndex: =5

    TextInput8 As text:
        BorderColor: =RGBA(245, 245, 245, 1)
        BorderThickness: =2
        Color: =RGBA(50, 49, 48, 1)
        Default: ="Valoranos"
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(161, 159, 157, 1)
        DisabledFill: =RGBA(242, 242, 241, 0)
        FocusedBorderThickness: =4
        Font: =Font.'Segoe UI'
        Height: =70
        HoverBorderColor: =RGBA(16, 110, 190, 1)
        HoverColor: =RGBA(50, 49, 48, 1)
        HoverFill: =RGBA(255, 255, 255, 1)
        PressedBorderColor: =RGBA(0, 120, 212, 1)
        PressedColor: =RGBA(50, 49, 48, 1)
        PressedFill: =RGBA(255, 255, 255, 1)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =21
        Width: =560
        X: =20
        Y: =450
        ZIndex: =6

    TextInput9 As text:
        BorderColor: =RGBA(245, 245, 245, 1)
        BorderThickness: =2
        Color: =RGBA(50, 49, 48, 1)
        Default: ="Tema"
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(161, 159, 157, 1)
        DisabledFill: =RGBA(242, 242, 241, 0)
        FocusedBorderThickness: =4
        Font: =Font.'Segoe UI'
        Height: =70
        HoverBorderColor: =RGBA(16, 110, 190, 1)
        HoverColor: =RGBA(50, 49, 48, 1)
        HoverFill: =RGBA(255, 255, 255, 1)
        PressedBorderColor: =RGBA(0, 120, 212, 1)
        PressedColor: =RGBA(50, 49, 48, 1)
        PressedFill: =RGBA(255, 255, 255, 1)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =21
        Width: =560
        X: =20
        Y: =560
        ZIndex: =7

    TextInput10 As text:
        BorderColor: =RGBA(245, 245, 245, 1)
        BorderThickness: =2
        Color: =RGBA(50, 49, 48, 1)
        Default: ="Entrada de texto"
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(161, 159, 157, 1)
        DisabledFill: =RGBA(242, 242, 241, 0)
        FocusedBorderThickness: =4
        Font: =Font.'Segoe UI'
        Height: =70
        HoverBorderColor: =RGBA(16, 110, 190, 1)
        HoverColor: =RGBA(50, 49, 48, 1)
        HoverFill: =RGBA(255, 255, 255, 1)
        PressedBorderColor: =RGBA(0, 120, 212, 1)
        PressedColor: =RGBA(50, 49, 48, 1)
        PressedFill: =RGBA(255, 255, 255, 1)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =21
        Width: =560
        X: =20
        Y: =663
        ZIndex: =8

